#!/bin/bash

make clean
make
echo "\n"

echo -e "\n\033[1;32m ------------------------------------------------------------------------------- \n \033[0m "

clear

for image in images/*.jp*g
do

	#  get image name without the extension
	image_name=$(echo $image | sed -n 's/images\/\(.*\)/\1/p')
	echo -e "\n Image name: $image_name"

	bin/jpeg2ppm "$image"

	echo -e "\033[1;32m ------------------------------------------------------------------------------- \033[0m "
done
